---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-deployment
  labels:
    app: fastapi-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: fastapi-app
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: fastapi-app
    spec:
      containers:
        - name: fastapi-container
          image: hw4-fastapi-app:v1
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          resources:
            limits:
              cpu: "2"
              memory: "2500Mi"
            requests:
              cpu: "1"
              memory: "200Mi"
